# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bossd/Documents/maya/2019/scripts/Thesis/ui_bk/editui.ui'
#
# Created: Mon Nov 23 12:12:09 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(1111, 690)
        self.centralwidget = QtWidgets.QWidget(Editor)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 941, 591))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.Info_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.Info_layout.setContentsMargins(0, 0, 0, 0)
        self.Info_layout.setObjectName("Info_layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Renderer_comboBox_1 = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Renderer_comboBox_1.setFont(font)
        self.Renderer_comboBox_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Renderer_comboBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Renderer_comboBox_1.setEditable(False)
        self.Renderer_comboBox_1.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.Renderer_comboBox_1.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.Renderer_comboBox_1.setObjectName("Renderer_comboBox_1")
        self.Renderer_comboBox_1.addItem("")
        self.Renderer_comboBox_1.addItem("")
        self.Renderer_comboBox_1.addItem("")
        self.Renderer_comboBox_1.addItem("")
        self.verticalLayout_2.addWidget(self.Renderer_comboBox_1)
        self.Info_renderer_Tree_1 = QtWidgets.QTreeWidget(self.horizontalLayoutWidget_3)
        self.Info_renderer_Tree_1.setObjectName("Info_renderer_Tree_1")
        item_0 = QtWidgets.QTreeWidgetItem(self.Info_renderer_Tree_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_2.addWidget(self.Info_renderer_Tree_1)
        self.Info_layout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Renderer_comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Renderer_comboBox_2.setFont(font)
        self.Renderer_comboBox_2.setObjectName("Renderer_comboBox_2")
        self.Renderer_comboBox_2.addItem("")
        self.Renderer_comboBox_2.addItem("")
        self.Renderer_comboBox_2.addItem("")
        self.Renderer_comboBox_2.addItem("")
        self.verticalLayout_3.addWidget(self.Renderer_comboBox_2)
        self.Info_renderer_Tree_2 = QtWidgets.QTreeWidget(self.horizontalLayoutWidget_3)
        self.Info_renderer_Tree_2.setObjectName("Info_renderer_Tree_2")
        self.Info_renderer_Tree_2.headerItem().setText(0, "Vray")
        item_0 = QtWidgets.QTreeWidgetItem(self.Info_renderer_Tree_2)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout_3.addWidget(self.Info_renderer_Tree_2)
        self.Info_layout.addLayout(self.verticalLayout_3)
        self.add_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.add_button.setObjectName("add_button")
        self.Info_layout.addWidget(self.add_button)
        self.Convert_info_tree = QtWidgets.QTreeWidget(self.horizontalLayoutWidget_3)
        self.Convert_info_tree.setObjectName("Convert_info_tree")
        self.Info_layout.addWidget(self.Convert_info_tree)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(980, 30, 121, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Button_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Button_Layout.setSpacing(10)
        self.Button_Layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.Button_Layout.setContentsMargins(0, 0, 0, 0)
        self.Button_Layout.setObjectName("Button_Layout")
        self.Clear_sl_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear_sl_button.sizePolicy().hasHeightForWidth())
        self.Clear_sl_button.setSizePolicy(sizePolicy)
        self.Clear_sl_button.setMaximumSize(QtCore.QSize(115, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clear_sl_button.setFont(font)
        self.Clear_sl_button.setObjectName("Clear_sl_button")
        self.Button_Layout.addWidget(self.Clear_sl_button)
        self.Clear_all_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Clear_all_button.sizePolicy().hasHeightForWidth())
        self.Clear_all_button.setSizePolicy(sizePolicy)
        self.Clear_all_button.setMinimumSize(QtCore.QSize(0, 0))
        self.Clear_all_button.setMaximumSize(QtCore.QSize(115, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Clear_all_button.setFont(font)
        self.Clear_all_button.setObjectName("Clear_all_button")
        self.Button_Layout.addWidget(self.Clear_all_button)
        self.add_inverse_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_inverse_button.sizePolicy().hasHeightForWidth())
        self.add_inverse_button.setSizePolicy(sizePolicy)
        self.add_inverse_button.setMaximumSize(QtCore.QSize(115, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_inverse_button.setFont(font)
        self.add_inverse_button.setObjectName("add_inverse_button")
        self.Button_Layout.addWidget(self.add_inverse_button)
        self.Save_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save_button.sizePolicy().hasHeightForWidth())
        self.Save_button.setSizePolicy(sizePolicy)
        self.Save_button.setMaximumSize(QtCore.QSize(115, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Save_button.setFont(font)
        self.Save_button.setObjectName("Save_button")
        self.Button_Layout.addWidget(self.Save_button)
        Editor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Editor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1111, 26))
        self.menubar.setObjectName("menubar")
        Editor.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(Editor)
        self.statusBar.setObjectName("statusBar")
        Editor.setStatusBar(self.statusBar)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        Editor.setWindowTitle(QtWidgets.QApplication.translate("Editor", "MainWindow", None, -1))
        self.Renderer_comboBox_1.setItemText(0, QtWidgets.QApplication.translate("Editor", "Arnold", None, -1))
        self.Renderer_comboBox_1.setItemText(1, QtWidgets.QApplication.translate("Editor", "Vray", None, -1))
        self.Renderer_comboBox_1.setItemText(2, QtWidgets.QApplication.translate("Editor", "Redshift", None, -1))
        self.Renderer_comboBox_1.setItemText(3, QtWidgets.QApplication.translate("Editor", "Renderman", None, -1))
        self.Info_renderer_Tree_1.headerItem().setText(0, QtWidgets.QApplication.translate("Editor", "Arnold", None, -1))
        __sortingEnabled = self.Info_renderer_Tree_1.isSortingEnabled()
        self.Info_renderer_Tree_1.setSortingEnabled(False)
        self.Info_renderer_Tree_1.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("Editor", "aiStandardSurface", None, -1))
        self.Info_renderer_Tree_1.topLevelItem(0).child(0).setText(0, QtWidgets.QApplication.translate("Editor", "Base", None, -1))
        self.Info_renderer_Tree_1.setSortingEnabled(__sortingEnabled)
        self.Renderer_comboBox_2.setItemText(0, QtWidgets.QApplication.translate("Editor", "Vray", None, -1))
        self.Renderer_comboBox_2.setItemText(1, QtWidgets.QApplication.translate("Editor", "Renderman", None, -1))
        self.Renderer_comboBox_2.setItemText(2, QtWidgets.QApplication.translate("Editor", "Redshift", None, -1))
        self.Renderer_comboBox_2.setItemText(3, QtWidgets.QApplication.translate("Editor", "Arnold", None, -1))
        __sortingEnabled = self.Info_renderer_Tree_2.isSortingEnabled()
        self.Info_renderer_Tree_2.setSortingEnabled(False)
        self.Info_renderer_Tree_2.topLevelItem(0).setText(0, QtWidgets.QApplication.translate("Editor", "VrayMtl", None, -1))
        self.Info_renderer_Tree_2.topLevelItem(0).child(0).setText(0, QtWidgets.QApplication.translate("Editor", "Diffuse", None, -1))
        self.Info_renderer_Tree_2.setSortingEnabled(__sortingEnabled)
        self.add_button.setText(QtWidgets.QApplication.translate("Editor", ">", None, -1))
        self.Convert_info_tree.headerItem().setText(0, QtWidgets.QApplication.translate("Editor", "Arnold", None, -1))
        self.Convert_info_tree.headerItem().setText(1, QtWidgets.QApplication.translate("Editor", "Vary", None, -1))
        self.Convert_info_tree.headerItem().setText(2, QtWidgets.QApplication.translate("Editor", "Inverse", None, -1))
        self.Clear_sl_button.setText(QtWidgets.QApplication.translate("Editor", "Clear Select", None, -1))
        self.Clear_all_button.setText(QtWidgets.QApplication.translate("Editor", "Clear All", None, -1))
        self.add_inverse_button.setText(QtWidgets.QApplication.translate("Editor", "Inverse value", None, -1))
        self.Save_button.setText(QtWidgets.QApplication.translate("Editor", "Save", None, -1))

