# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/bossd/Documents/maya/2019/scripts/ShaderConvertor/ui_bk/ui.ui'
#
# Created: Fri Dec 18 14:52:59 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ShaderConvertor(object):
    def setupUi(self, ShaderConvertor):
        ShaderConvertor.setObjectName("ShaderConvertor")
        ShaderConvertor.resize(803, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShaderConvertor.sizePolicy().hasHeightForWidth())
        ShaderConvertor.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ShaderConvertor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Select_layout = QtWidgets.QHBoxLayout()
        self.Select_layout.setObjectName("Select_layout")
        self.Preset_label = QtWidgets.QLabel(self.centralwidget)
        self.Preset_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Preset_label.sizePolicy().hasHeightForWidth())
        self.Preset_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Preset_label.setFont(font)
        self.Preset_label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Preset_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Preset_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Preset_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Preset_label.setObjectName("Preset_label")
        self.Select_layout.addWidget(self.Preset_label)
        self.Preset_combo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Preset_combo.sizePolicy().hasHeightForWidth())
        self.Preset_combo.setSizePolicy(sizePolicy)
        self.Preset_combo.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Preset_combo.setFont(font)
        self.Preset_combo.setObjectName("Preset_combo")
        self.Preset_combo.addItem("")
        self.Preset_combo.addItem("")
        self.Select_layout.addWidget(self.Preset_combo)
        self.EditPreset_button = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditPreset_button.sizePolicy().hasHeightForWidth())
        self.EditPreset_button.setSizePolicy(sizePolicy)
        self.EditPreset_button.setMaximumSize(QtCore.QSize(30, 30))
        self.EditPreset_button.setObjectName("EditPreset_button")
        self.Select_layout.addWidget(self.EditPreset_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Select_layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.Select_layout)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.treeWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.treeWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.treeWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.treeWidget.setLineWidth(1)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setDefaultSectionSize(206)
        self.verticalLayout.addWidget(self.treeWidget)
        self.reload_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reload_button.sizePolicy().hasHeightForWidth())
        self.reload_button.setSizePolicy(sizePolicy)
        self.reload_button.setMinimumSize(QtCore.QSize(0, 31))
        self.reload_button.setMaximumSize(QtCore.QSize(16777215, 100000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reload_button.setFont(font)
        self.reload_button.setObjectName("reload_button")
        self.verticalLayout.addWidget(self.reload_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.Convert_Layout = QtWidgets.QVBoxLayout()
        self.Convert_Layout.setObjectName("Convert_Layout")
        self.Delete_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Delete_checkBox.setFont(font)
        self.Delete_checkBox.setChecked(True)
        self.Delete_checkBox.setObjectName("Delete_checkBox")
        self.Convert_Layout.addWidget(self.Delete_checkBox)
        self.Convert_Button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Convert_Button.sizePolicy().hasHeightForWidth())
        self.Convert_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Convert_Button.setFont(font)
        self.Convert_Button.setObjectName("Convert_Button")
        self.Convert_Layout.addWidget(self.Convert_Button)
        self.verticalLayout_2.addLayout(self.Convert_Layout)
        ShaderConvertor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ShaderConvertor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 26))
        self.menubar.setObjectName("menubar")
        ShaderConvertor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ShaderConvertor)
        self.statusbar.setObjectName("statusbar")
        ShaderConvertor.setStatusBar(self.statusbar)

        self.retranslateUi(ShaderConvertor)
        QtCore.QMetaObject.connectSlotsByName(ShaderConvertor)

    def retranslateUi(self, ShaderConvertor):
        ShaderConvertor.setWindowTitle(QtWidgets.QApplication.translate("ShaderConvertor", "MainWindow", None, -1))
        self.Preset_label.setText(QtWidgets.QApplication.translate("ShaderConvertor", "Select Preset:", None, -1))
        self.Preset_combo.setItemText(0, QtWidgets.QApplication.translate("ShaderConvertor", "arnold_to_vray", None, -1))
        self.Preset_combo.setItemText(1, QtWidgets.QApplication.translate("ShaderConvertor", "--- create new preset ---", None, -1))
        self.EditPreset_button.setText(QtWidgets.QApplication.translate("ShaderConvertor", "Edit", None, -1))
        self.treeWidget.headerItem().setText(0, QtWidgets.QApplication.translate("ShaderConvertor", "Shader", None, -1))
        self.treeWidget.headerItem().setText(1, QtWidgets.QApplication.translate("ShaderConvertor", "Object", None, -1))
        self.reload_button.setText(QtWidgets.QApplication.translate("ShaderConvertor", "Reload", None, -1))
        self.Delete_checkBox.setText(QtWidgets.QApplication.translate("ShaderConvertor", "Delete old Shaders", None, -1))
        self.Convert_Button.setText(QtWidgets.QApplication.translate("ShaderConvertor", "Convert", None, -1))

